image: debian:bullseye

build:
  stage: build
  before_script:
    - apt update && apt install -y git
    - git submodule update --init --recursive
    - ./setup.sh
  script:
    - ./build.sh
  artifacts:
    paths:
      - mybinary

# run tests using the binary built before
test:
  stage: test
  script:
    - ./test.sh

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - main
