image: ruby:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  stage: deploy
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "blog"
  environment: production
